### ISSUE TITLE
Having a 'Deprecated' notice on the first page of the Getting Started is likely to reduce community participation

### ISSUE THREAD

**Issue by pacharanero** [AppertaFoundation/openeyes#1]
![image](https://user-images.githubusercontent.com/2348385/35150251-9d1ceb94-fd11-11e7-83b1-a0096b194606.png)

**Comment by pacharanero** [comment]
https://github.com/AppertaFoundation/openeyes/wiki/Quick-Start

**Comment by biskyt** [comment]
Made a quick edit to point to the most up-to-date info. Nobody is currently maintaining the wiki
