### ISSUE TITLE
Problem with installation 

### ISSUE THREAD

**Issue by Yonyzzz** [AppertaFoundation/openeyes#14]
Hello,
When I try to install it through an Ubuntu 18.04 server on virtual box 
Following the step you gave 
I get to the fourth step (Run sudo bash /var/www/openeyes/protected/scripts/install-system.sh) 
And I get nom errors about dependencies 
Hope someone can help me out
Thank you

**Comment by Yonyzzz** [comment]
even the docker container isn't working any more  php npm errors and fatal errors 
any one who have solution for this please ?

**Comment by PaulGWebster** [comment]
Zero, I got passed the install-system.sh but the install-oe is broken instead (the next step)

`Migrations were not run automaically. If you need to run the database migrations, run script /var/www/openeyes/protected/scripts/oe-migrate.sh

Adding user root to group www-data

Resetting file permissions...
ownership of /var/www/openeyes looks ok, skipping. Use --force-perms to override
updating /var/www/openeyes/protected/config/local to 774...
updating /var/www/openeyes/assets/ to 774...
updating /var/www/openeyes/protected/runtime to 774...
updating /var/www/openeyes/protected/files to 774...
setting sticky bit for protected/runtime
setting sticky bit for protected/files

...Done

DB migrations will not run automatically
Unknown Parameter(s):

******************************************
*** AN ERROR OCCURRED - CHECK THE LOGS ***
******************************************
root@a04462cfceeb:/var/www# /var/www/openeyes/protected/scripts/oe-migrate.sh
Couldn't find yiic.php.
Couldn't find yiic.php.
No new migrations to apply - see /var/www/openeyes/protected/runtime/migrate.log for more details`

**Comment by mahevstark** [comment]
@PaulGWebster can you please provide an overview how you got past the errors in install-system.sh step?

**Comment by DrJohnDavis** [comment]
Is there YouTube tutorial for OpenEyes Installation ?

I’m able to fond only for OpenEMR not for OpenEyes

**Comment by mahevstark** [comment]
@DrJohnDavis  I could record one for you but this repo is not functional, it's depending on another repo which doesn't even exist on given path anymore. Please reach out if you find anything. My team has on it for months, but no luck

**Comment by DrJohnDavis** [comment]
> @DrJohnDavis I could record one for you but this repo is not functional, it's depending on another repo which doesn't even exist on given path anymore. Please reach out if you find anything. My team has on it for months, but no luck

Thanks. I am trying to download and install OpenEyes EMR to a Windows Machine.
Is there a different repo or a easy installation version that is made for beginners ?

Which dependencies are missing ? Would Apperta be able to give the download links ?

**Comment by paulgwebster-oe** [comment]
> @PaulGWebster can you please provide an overview how you got past the errors in install-system.sh step?

Sorry for the long reply, I am currently in the process of actually creating a fully working OE and will update this tracker when I have good news :)

**Comment by DrJohnDavis** [comment]
Any updates ? Is this possible to install only on a Linux computer ?

**Comment by DrJohnDavis** [comment]
[Open Eyes - Windows Server Setup - link 1](https://silo.tips/download/openeyes-windows-server-setup-openeyes-windows-server-setup)

[Open Eyes - Windows Server Setup - link 2](https://docplayer.net/10792470-Openeyes-windows-server-setup-openeyes-windows-server-setup.html)

**Comment by DrJohnDavis** [comment]
> > @PaulGWebster can you please provide an overview how you got past the errors in install-system.sh step?
> 
> Sorry for the long reply, I am currently in the process of actually creating a fully working OE and will update this tracker when I have good news :)

Any good news ?

Were you able to install a working OpenEyes ?

**Comment by jeevanism** [comment]
any updates here ?
