### ISSUE TITLE
Node Error while running the dependcies 

### ISSUE THREAD

**Issue by ram58** [AppertaFoundation/openeyes#17]
WARN engine npm@9.7.1: wanted: {"node":"^14.17.0 || ^16.13.0 || >=18.0.0"} (current: {"nod
e":"8.10.0","npm":"3.5.2"})
WARN engine npm@9.7.1: wanted: {"node":"^14.17.0 || ^16.13.0 || >=18.0.0"} (current: {"nod
npm ERR! Linux 4.15.0-1021-aws
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "npm"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2

npm ERR! Unsupported URL Type: npm:string-width@^4.2.0
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/npm-debug.log
installing global npm dependencies
▄ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine grunt-cli@1.4.3: wanted: {"node":">=10"} (current: {"node":"8.10.0","npm":"3.5
.2"})
WARN engine grunt-cli@1.4.3: wanted: {"node":">=10"} (current: {"node":"8.10.0","npm":"3.5
loadDep:v8flags → request ▌ ╢████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine liftup@3.0.1: wanted: {"node":">=10"} (current: {"node":"8.10.0","npm":"3.5.2"
/usr/local/bin/grunt -> /usr/local/lib/node_modules/grunt-cli/bin/grunt
/usr/local/lib
└── grunt-cli@1.4.3 

Installing wkhtmltopdf...

--2023-06-08 18:24:20--  https://downloads.wkhtmltopdf.org/0.12/0.12.5/wkhtmltox_0.12.5-1.
bionic_amd64.deb
Resolving downloads.wkhtmltopdf.org (downloads.wkhtmltopdf.org)... failed: Name or service
 not known.
wget: unable to resolve host address ‘downloads.wkhtmltopdf.org’
******************************************
*** AN ERROR OCCURRED - CHECK THE LOGS ***
******************************************

**Comment by ram58** [comment]
Does anybody have any update ??

**Comment by DrJohnDavis** [comment]
Were you able to fix the issue ?

**Comment by ram58** [comment]
No!!
