### ISSUE TITLE
Can OpenEyes (server) be installed on a Windows computer ?

### ISSUE THREAD

**Issue by DrJohnDavis** [AppertaFoundation/openeyes#19]
The Setup instructions say Ubuntu Linux 18.06, but is it possible to install OpenEyes on a Windows computer instead ?

**Comment by DrJohnDavis** [comment]
Found these instructions.

[Open Eyes - Windows Server Setup - link 1](https://silo.tips/download/openeyes-windows-server-setup-openeyes-windows-server-setup)

[Open Eyes - Windows Server Setup - link 2](https://docplayer.net/10792470-Openeyes-windows-server-setup-openeyes-windows-server-setup.html)

Does it work ?

**Comment by morkser-hub** [comment]
can anyone please confirm it works?
