### ISSUE TITLE
Instead of Ubuntu on a standard computer, can OpenEyes Server potentially run on a Raspberry Pi ?

### ISSUE THREAD

**Issue by DrJohnDavis** [AppertaFoundation/openeyes#20]
Instead of Ubuntu on a standard computer, can OpenEyes Server potentially run on a Raspberry Pi ?
Not for heavy lifting, just for a small clinic ?

Is there any software issues with running on Raspbian Linux instead of Ubuntu ?

**Comment by scm7mae** [comment]
@DrJohnDavis I've got it installed on a Raspberry Pi on an ubuntu 22.04 image.  The only issue at this point is I cannot get the web login working....
