### ISSUE TITLE
Missing Libraries

### ISSUE THREAD

**Issue by aunsyed** [AppertaFoundation/openeyes#24]
Hello Dear AppertaFoundation Family,

I am trying to configure the code, I am stuck at Step4:
Step4: Run sudo bash /var/www/openeyes/protected/scripts/install-system.sh
(this installs and configures the necessary services, such as the Apache webserver)

it says missing libraries. Attaching the error screenshot here:

<img width="323" alt="Step4 Error" src="https://github.com/AppertaFoundation/openeyes/assets/6693193/013431d2-692f-4a0a-acff-9af3106aafd7">

Can you please advise on this?
Your support will be much appreciated.

**Comment by scm7mae** [comment]
Try following the instructions instead on Ubuntu 22.04 LTS.  That will then be more successful.  You will hit other issues around missing frameworks, but at least you'll be able to install it
