### ISSUE TITLE
receiving error when trying to install

### ISSUE THREAD

**Issue by syedmdu** [AppertaFoundation/openeyes#30]
I am trying to configure openeye with the below o.s but receiving error 
after running the Bash cmd install-system.sh script
 
Run sudo bash /var/www/openeyes/protected/scripts/install-system.sh
Welcome to Ubuntu 18.04.6 LTS (GNU/Linux 4.15.0-213-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Thu Mar 21 10:27:48 UTC 2024

  System load:  0.12              Processes:            102
  Usage of /:   7.9% of 72.78GB   Users logged in:      0
  Memory usage: 1%                IP address for ens18: 172.17.9.92
  Swap usage:   0%

Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
Installing required system packages
---= installing  packages =---
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'php5.6-json' for regex 'php5.6'
Note, selecting 'php5.6-common' for regex 'php5.6'
E: Unable to locate package php5.6-mbstring
E: Couldn't find any package by glob 'php5.6-mbstring'
E: Couldn't find any package by regex 'php5.6-mbstring'
E: Unable to locate package php5.6-cli
E: Couldn't find any package by glob 'php5.6-cli'
E: Couldn't find any package by regex 'php5.6-cli'
E: Unable to locate package php5.6-mysql
E: Couldn't find any package by glob 'php5.6-mysql'
E: Couldn't find any package by regex 'php5.6-mysql'
E: Unable to locate package php5.6-ldap
E: Couldn't find any package by glob 'php5.6-ldap'
E: Couldn't find any package by regex 'php5.6-ldap'
E: Unable to locate package php5.6-curl
E: Couldn't find any package by glob 'php5.6-curl'
E: Couldn't find any package by regex 'php5.6-curl'
E: Unable to locate package php5.6-xsl
E: Couldn't find any package by glob 'php5.6-xsl'
E: Couldn't find any package by regex 'php5.6-xsl'
E: Unable to locate package php5.6-gd
E: Couldn't find any package by glob 'php5.6-gd'
E: Couldn't find any package by regex 'php5.6-gd'
E: Unable to locate package php5.6-mcrypt
E: Couldn't find any package by glob 'php5.6-mcrypt'
E: Couldn't find any package by regex 'php5.6-mcrypt'
E: Unable to locate package php5.6-imagick
E: Couldn't find any package by glob 'php5.6-imagick'
E: Couldn't find any package by regex 'php5.6-imagick'
E: Unable to locate package php5.6-zip
E: Couldn't find any package by glob 'php5.6-zip'
E: Couldn't find any package by regex 'php5.6-zip'
E: Unable to locate package libapache2-mod-php5.6
E: Couldn't find any package by glob 'libapache2-mod-php5.6'
E: Couldn't find any package by regex 'libapache2-mod-php5.6'
******************************************
*** AN ERROR OCCURRED - CHECK THE LOGS ***
******************************************

**Comment by AtharvaMohite07** [comment]
I am getting the same issue can anyone reply one this?
