### ISSUE TITLE
Demo database ZIP is corrupted 

### ISSUE THREAD

**Issue by mikeyd85** [AppertaFoundation/openeyes#46]
Hello,

Whenever I download the demo database ZIP as per the wiki, I am unable to open it. This is true on both Windows and Linux.

Can the ZIP please be replaced?

Thanks.

**Comment by gabordikan** [comment]
Hello @mikeyd85,

The file is compressed with gzip. You can unzip it with `zcat` or just rename it to .gz and use `gunzip` to decompress the file.

Regards,
Gabor

**Comment by mikeyd85** [comment]
Thanks @gabordikan. Might be worth updating the wiki and renaming the file. I suspect others will find the same problem.

**Comment by jeevanism** [comment]
this command works fine 

`zcat sample_db.zip > sample_db.sql`
