### ISSUE TITLE
Error In Install-system.sh

### ISSUE THREAD

**Issue by AtharvaMohite07** [AppertaFoundation/openeyes#48]
Error found after: 
sudo bash /var/www/openeyes/protected/scripts/install-system.sh

Error:
STARTING SYSTEM INSATLL IN MODE: ...

vm.swappiness = 10
Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:3 http://security.ubuntu.com/ubuntu bionic-security InRelease
Hit:4 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
Hit:5 http://ppa.launchpad.net/ondrej/php/ubuntu bionic InRelease
Reading package lists... Done
grub-pc set on hold.
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
software-properties-common is already the newest version (0.96.24.32.22).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:3 http://ppa.launchpad.net/ondrej/php/ubuntu bionic InRelease
Hit:4 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
Hit:5 http://security.ubuntu.com/ubuntu bionic-security InRelease
Reading package lists... Done
Performing package updates
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Installing required system packages
---= installing  packages =---
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'php5.6-json' for regex 'php5.6'
Note, selecting 'php5.6-common' for regex 'php5.6'
E: Unable to locate package php5.6-mbstring
E: Couldn't find any package by glob 'php5.6-mbstring'
E: Couldn't find any package by regex 'php5.6-mbstring'
E: Unable to locate package php5.6-cli
E: Couldn't find any package by glob 'php5.6-cli'
E: Couldn't find any package by regex 'php5.6-cli'
E: Unable to locate package php5.6-mysql
E: Couldn't find any package by glob 'php5.6-mysql'
E: Couldn't find any package by regex 'php5.6-mysql'
E: Unable to locate package php5.6-ldap
E: Couldn't find any package by glob 'php5.6-ldap'
E: Couldn't find any package by regex 'php5.6-ldap'
E: Unable to locate package php5.6-curl
E: Couldn't find any package by glob 'php5.6-curl'
E: Couldn't find any package by regex 'php5.6-curl'
E: Unable to locate package php5.6-xsl
E: Couldn't find any package by glob 'php5.6-xsl'
E: Couldn't find any package by regex 'php5.6-xsl'
E: Unable to locate package php5.6-gd
E: Couldn't find any package by glob 'php5.6-gd'
E: Couldn't find any package by regex 'php5.6-gd'
E: Unable to locate package php5.6-mcrypt
E: Couldn't find any package by glob 'php5.6-mcrypt'
E: Couldn't find any package by regex 'php5.6-mcrypt'
E: Unable to locate package php5.6-imagick
E: Couldn't find any package by glob 'php5.6-imagick'
E: Couldn't find any package by regex 'php5.6-imagick'
E: Unable to locate package php5.6-zip
E: Couldn't find any package by glob 'php5.6-zip'
E: Couldn't find any package by regex 'php5.6-zip'
E: Unable to locate package libapache2-mod-php5.6
E: Couldn't find any package by glob 'libapache2-mod-php5.6'
E: Couldn't find any package by regex 'libapache2-mod-php5.6'
******************************************
*** AN ERROR OCCURRED - CHECK THE LOGS ***
******************************************

**Comment by gabordikan** [comment]
Hi @AtharvaMohite07,

this script is outdated and only suitable for version 1.19. Please follow steps in the Installation instruction

Regards,
Gábor
