### ISSUE TITLE
Upgrading from v4.0.4 or v.4.2 to 5.0.8 breaks sign in screen

### ISSUE THREAD

**Issue by usrErr0r** [AppertaFoundation/openeyes#50]
Ubuntu Server 20.04

Upon following the steps exactly to upgrade from version 4.0.4 and 4.2 to 5.0.8, the login screen breaks, complaining about device width. The sign in is also broken, stating that "Site Id cannot be blank."

![image](https://github.com/user-attachments/assets/37147af7-e47a-4f2c-84c8-25a82f514b13)

I have attempted this a few times with no success unfortunately

**Comment by gabordikan** [comment]
Hi @usrErr0r,

Can you please verify these steps:
- NewBlue is available in /protected/assets/newblue directory
- Files are deleted and regenerated in directory /assets/
- page opened in incognito mode (skip client caching)

Thanks,
Gábor
