### ISSUE TITLE
Is it possible for novices to use this system

### ISSUE THREAD

**Issue by drswapnil** [AppertaFoundation/openeyes#7]
Dear sir,

I am a novice in the field but would love to try out the system. Could you pls guide how to install the same on a windows desktop. Thanks

**Comment by LeoZandvliet** [comment]
I haven't installed or used this software yet, but it would be needed that you have at least some experience running websites locally on your desktop.
[Please read this wiki for windows](https://github.com/AppertaFoundation/openeyes/wiki/Installing-OpenEyes-on-Windows-7-SP1)
