### ISSUE TITLE
Help intalling OE on ubuntu 18.04

### ISSUE THREAD

**Issue by barrydocks2** [AppertaFoundation/openeyes#8]
Having a go at installing OE on ubuntu 18.04. I have been trying to use the wiki how to but most of the stuff in based on 14.04 and old versions of OE.

I get as far as:

```
sudo ./yiic migrate
Couldn't find yiic.php.
```
Can any one give me help please?

**Comment by biskyt** [comment]
Please see the Setup section of the Readme on the front page https://github.com/AppertaFoundation/openeyes#setup

**Comment by barrydocks2** [comment]
> 
> 
> Please see the Setup section of the Readme on the front page https://github.com/AppertaFoundation/openeyes#setup

I have tried this, I managed to get the docker application to work but i want to install as a clean install it from github, mainly as I can't use docker very well but also I don't want any data
