### ISSUE TITLE
AGPL License Violation

### ISSUE THREAD

**Issue by sickcodes** [AppertaFoundation/openeyes#9]
Please upload the development branches as any changes or modifications to the code must be published.

**Comment by sickcodes** [comment]
Requesting an update, is this project AGPL or not?

**Comment by sickcodes** [comment]
https://www.gnu.org/licenses/gpl-violation.en.html

**Comment by sickcodes** [comment]
Please send me a copy of the source code of OpenEyes v4: info at sick.codes

**Comment by robdyke** [comment]
@sickcodes

>Q: Can the software be developed and sold?
>A: If you have developed and contributed to any open source software, the modifications that have been made to the code must be fed back into the community at no cost. Consequently, the new modified version you have created is then also available free of charge. If appropriate you may wish to offer implementation or support services to organisations wishing to use the software.

Source: [NHS England Open Source Team](https://www.webarchive.org.uk/wayback/en/archive/20171001165906/https://www.england.nhs.uk/digitaltechnology/info-revolution/open-source/os-faqs/)

**Comment by robdyke** [comment]
@sickcodes I don't think there is a version 4 of openEyes.

@biskyt tagged a [release of newblue as v4.0](https://github.com/openeyes/newblue/releases/tag/v4.0) in January 2021.

The [README for newblue has just been updated](https://github.com/openeyes/newblue/commit/0c03b765e1cdbb2f070649ce13ad511bda36029c?short_path=b335630#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5) by @biskyt which makes it clear that newblue is just a new UI for the v3 release

**Comment by sickcodes** [comment]
Closed source now I guess
